// <auto-generated />
namespace Sistema_de_Prestamo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AgregadoCampoPagado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregadoCampoPagado));
        
        string IMigrationMetadata.Id
        {
            get { return "202204011336550_AgregadoCampoPagado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
