// <auto-generated />
namespace Sistema_de_Prestamo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202203310007535_Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
