// <auto-generated />
namespace Sistema_de_Prestamo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mora_type_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mora_type_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "202204111511231_mora_type_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
